IOS-2370
tangem/exchange-sdk-swift pull request #1
Opened 2022-10-21 10:51 UTC by gre4ixin

2022-10-24 11:56 UTC, megakoko requested changes

2022-10-24 11:56 UTC, megakoko commented on Sources/Exchanger/Public/Models/ParametersObject/LimitOrderParameters.swift
> +        params["statuses"] = "\(statuses.map({ $0.rawValue }).sorted())"
Тут нужна сортировка?

2022-10-24 11:56 UTC, megakoko commented on Tests/ExchangerTests/LimitTests.swift
> +        print(params.parameters())
Можно просто OrdersAllParameters(...)

print тут нужен?

2022-10-25 14:59 UTC, gre4ixin commented on ExchangerExample/ExchangerExample/ContentView.swift
> +    }
Я для проверки работы Cocoapods делал, чтобы убедиться, что оно правильно подтягивается

2022-10-25 15:00 UTC, gre4ixin commented on ExchangerExample/Podfile
> +  pod 'Exchanger', :git => 'https://github.com/gre4ixin/Exchanger.git', :tag => '1.0.4'
я хочу подспеку обновить после залития в девелоп, чтобы проставить тег с версией и все еще раз проверить, пока главная ветка пуста все равно не работает ничего

2022-10-25 15:02 UTC, gre4ixin commented on Exchanger.podspec
> +    s.license = { :type => "MIT", :file => "LICENSE" }
закомментировал, как и в blockchainSdk, уточню у Андрея что там выбираем

2022-10-26 04:10 UTC, megakoko commented on ExchangerExample/ExchangerExample/ContentView.swift
> +    }
Можно удалить?

2022-10-26 04:15 UTC, megakoko commented on Sources/Exchanger/API/ExchangeTargets/InfoTarget.swift
> +    //List of presets configurations for the 1inch router
Пройди еще по проекту с регуляркой "//[^\s/]"

2022-10-26 04:16 UTC, megakoko commented on Sources/Exchanger/API/ExchangeTargets/InfoTarget.swift
> +            return .requestPlain
Можно просто без свитча возвращать чтобы код проще был

2022-10-26 04:17 UTC, megakoko commented on Sources/Exchanger/API/LimitTargets/LimitOrder.swift
> +    case ordersForAddress(blockchain: ExchangeBlockchain, parameters: OrdersForAddressParameters)
В NetworkFacade не выровнены

2022-10-26 04:19 UTC, megakoko commented on Sources/Exchanger/Network/NetworkFacade.swift
> +    func request<T: Decodable>(with target: DexTarget, decodeTo: T.Type) -> AnyPublisher<T, ExchangeError> {
Комбайн не нужен?

2022-10-26 04:21 UTC, megakoko commented on Sources/Exchanger/Public/ExchangeFacade.swift
> +    }
Без этого не обойтись?

```
switch response {
case .success(let decodedResponse):
    return .success(decodedResponse)
case .failure(let error):
    return .failure(error)
}
```

2022-10-26 04:22 UTC, megakoko commented on Sources/Exchanger/Public/ExchangeFacade.swift
> +    public func presents(blockchain: ExchangeBlockchain) async -> Result<PresentsConfigurationDTO, ExchangeError> {
В тестах осталось

2022-10-26 04:22 UTC, megakoko commented on Sources/Exchanger/Public/LimitOrderFacade.swift
> +    /// - Returns: result request
Давай из ExchangingFacade тоже удалим

2022-10-26 04:23 UTC, megakoko commented on Sources/Exchanger/Public/Models/DTO/InfoDTO.swift
> +    public let eip2612, isFoT: Bool?
Еще LimitOrderDTO.MetaData

2022-10-26 04:23 UTC, megakoko commented on Sources/Exchanger/Public/Models/DTO/LimitOrderDTO.swift
> +public struct LimitOrderModel: Codable {
Все модели удалил?

2022-10-26 04:24 UTC, megakoko commented on Sources/Exchanger/Public/Models/ParametersObject/LimitOrderParameters.swift
> +    public var statuses: [Statuses] = []
AllOrdersParameters? Посмотри еще по проекту где можно убрать.

2022-10-26 04:26 UTC, megakoko commented on ExchangerExample/Podfile
> +  pod 'Exchanger', :git => 'https://github.com/gre4ixin/Exchanger.git', :tag => '1.0.4'
В подспеке название ExchangeSDK. Давай переименуем в ExchangeSdk. SDK правильнее, но в других репозиториях уже Sdk используется.

2022-10-26 10:39 UTC, gre4ixin commented on Sources/Exchanger/Public/Models/ParametersObject/LimitOrderParameters.swift
> +        params["statuses"] = "\(statuses.map({ $0.rawValue }).sorted())"
сортировка параметров нужна

2022-10-26 21:14 UTC, gre4ixin commented on ExchangerExample/ExchangerExample/ContentView.swift
> +    }
ну в целом можно и удалить, все в тестах есть

2022-10-26 21:14 UTC, gre4ixin commented on ExchangerExample/Podfile
> +  pod 'Exchanger', :git => 'https://github.com/gre4ixin/Exchanger.git', :tag => '1.0.4'
✅

2022-10-26 21:15 UTC, gre4ixin commented on Sources/Exchanger/API/ExchangeTargets/InfoTarget.swift
> +    //List of presets configurations for the 1inch router
✅

2022-10-26 21:15 UTC, gre4ixin commented on Sources/Exchanger/API/ExchangeTargets/InfoTarget.swift
> +            return .requestPlain
✅

2022-10-26 21:16 UTC, gre4ixin commented on Sources/Exchanger/API/LimitTargets/LimitOrder.swift
> +    case ordersForAddress(blockchain: ExchangeBlockchain, parameters: OrdersForAddressParameters)
✅

2022-10-26 21:16 UTC, gre4ixin commented on Sources/Exchanger/API/LimitTargets/LimitOrder.swift
> +            let statuses = "\(parameters.map({ $0.rawValue }).sorted())"
да

2022-10-26 21:16 UTC, gre4ixin commented on Sources/Exchanger/Network/NetworkFacade.swift
> +    func request<T: Decodable>(with target: DexTarget, decodeTo: T.Type) -> AnyPublisher<T, ExchangeError> {
комбайн наружу никак не смотрит, убрал метод

2022-10-26 21:20 UTC, gre4ixin commented on Tests/ExchangerTests/LimitTests.swift
> +        print(params.parameters())
✅

2022-10-26 21:21 UTC, gre4ixin commented on Tests/ExchangerTests/LimitTests.swift
> +            XCTAssert(false)
✅

2022-10-27 06:06 UTC, gre4ixin commented on Sources/Exchanger/Public/ExchangeFacade.swift
> +    public func presents(blockchain: ExchangeBlockchain) async -> Result<PresentsConfigurationDTO, ExchangeError> {
✅

2022-10-27 06:07 UTC, gre4ixin commented on Sources/Exchanger/Public/LimitOrderFacade.swift
> +    /// - Returns: result request
✅

2022-10-27 06:11 UTC, gre4ixin commented on Sources/Exchanger/Public/Models/DTO/InfoDTO.swift
> +    public let eip2612, isFoT: Bool?
✅

2022-10-27 06:11 UTC, gre4ixin commented on Sources/Exchanger/Public/Models/DTO/LimitOrderDTO.swift
> +public struct LimitOrderModel: Codable {
все

2022-10-27 06:11 UTC, gre4ixin commented on Sources/Exchanger/Public/Models/DTO/LimitOrderDTO.swift
> +    public let result: Bool
начинать название модели с Has как-то не очень звучит

2022-10-27 07:16 UTC, gre4ixin commented on Sources/Exchanger/Public/Models/ParametersObject/LimitOrderParameters.swift
> +    public var statuses: [Statuses] = []
✅

2022-10-27 09:57 UTC, megakoko commented on Sources/Exchanger/Public/Models/DTO/LimitOrderDTO.swift
> +    public let result: Bool
Согласен, окей

2022-10-27 10:01 UTC, megakoko commented on Sources/Exchanger/Public/Models/DTO/LimitOrderDTO.swift
> +    public let result: Bool
Хотя не, смотри, возвращаем мы ActiveOrdersWithPermitDTO которое звучит как оно должно содержать список ордеров, а по факту у нее единственное поле — булевый result. Тоже не очень.

Давай уж либо переименуем DTO, или просто булевый результат возвращать будем, а DTO тогда сделаем internal чтоб не торчало.

2022-10-27 12:26 UTC, gre4ixin commented on Sources/Exchanger/Public/Models/DTO/LimitOrderDTO.swift
> +    public let result: Bool
✅

2022-10-27 13:54 UTC, megakoko approved these changes

2022-10-27 14:24 UTC, Balashov152 commented on Sources/ExchangeSDK/ExchangeSdk.swift
> +    public static private(set) var version = "1.0.0"
Может `let`, все равно же не меняется нигде

2022-10-27 14:24 UTC, Balashov152 commented on Sources/ExchangeSdk/Network/NetworkFacade.swift
> +                        print("URL REQUEST -> \(response.request?.url?.absoluteString ?? "")")
Как вариант, и если не лень, то можно сделать какой нибудь struct Logger
в который передавать лог с метками .info, .warning. .error
что бы потом можно было из этого же места куда нибудь отправлять, и искать баги

 и debugMode тоже можно там отслеживать

2022-10-27 14:24 UTC, Balashov152 commented on Sources/ExchangeSdk/Network/NetworkFacade.swift
> +                            continuation.resume(returning: .failure(.unknownError(statusCode: 500)))
statusCode: 500 это internalServer error,не будет путать потом?

2022-10-27 14:24 UTC, Balashov152 commented on Sources/ExchangeSdk/Public/Models/DTO/SwapDTO.swift
> +    public let protocols: [[[ProtocolElementDTO]]]
Тройной массив, мощно ))

2022-10-27 14:24 UTC, Balashov152 commented on Sources/ExchangeSdk/Public/Models/ParametersObject/ApproveParameters.swift
> +    }
Может лучше ecodable юзать
Что бы в Moya сразу передавать модель, да и все

Там те же самые проверки можно реализовать

2022-10-27 14:24 UTC, Balashov152 commented on Sources/ExchangeSdk/Public/Models/ParametersObject/ApproveParameters.swift
> +}
Для всех `parameters()`

2022-10-27 14:24 UTC, Balashov152 commented on Sources/ExchangeSdk/Public/Models/ParametersObject/SwapParameters.swift
> +        }
там есть encodeIfPresent(), или даже по умолчанию он не будет nil сериализовать

2022-10-28 07:32 UTC, gre4ixin commented on Sources/ExchangeSdk/Network/NetworkFacade.swift
> +                            continuation.resume(returning: .failure(.unknownError(statusCode: 500)))
поправил

2022-10-28 07:32 UTC, gre4ixin commented on Sources/ExchangeSDK/ExchangeSdk.swift
> +    public static private(set) var version = "1.0.0"
поправил

2022-10-28 07:34 UTC, gre4ixin commented on Sources/ExchangeSdk/Public/Models/ParametersObject/ApproveParameters.swift
> +    }
там ведь параметры в URL, а не в body

2022-10-28 07:49 UTC, gre4ixin commented on Sources/ExchangeSdk/Network/NetworkFacade.swift
> +                        print("URL REQUEST -> \(response.request?.url?.absoluteString ?? "")")
у нас вроде нет нигде логгеров таких в либах, все в приложении логируется, не факт, что это будет нужно в каком-то другом месте использования этой либы(

2022-10-28 11:48 UTC, Balashov152 commented on Sources/ExchangeSdk/Network/NetworkFacade.swift
> +                        print("URL REQUEST -> \(response.request?.url?.absoluteString ?? "")")
Ну ок, это как предложение

2022-10-28 14:24 UTC, Balashov152 approved these changes

2022-10-31 06:30 UTC, Andoran90 requested changes

2022-10-31 06:30 UTC, Andoran90 commented on Sources/ExchangeSdk/Public/Models/DTO/InfoDTO.swift
> +//  InfoDTO.swift
слишком много структур в одном файле. Лучше их разделить

2022-10-31 06:30 UTC, Andoran90 commented on Sources/ExchangeSdk/Public/Models/DTO/InfoDTO.swift
> +public struct InfoTokensDTO: Decodable {
мне кажется лучше назвать `TokensList`

2022-10-31 06:30 UTC, Andoran90 commented on Sources/ExchangeSdk/Public/Models/DTO/InfoDTO.swift
> +public struct TokenDTO: Decodable {
`ExchangeToken` чтобы не пересекался с Blockchain Sdk Token и чтобы не было DTO

2022-10-31 06:30 UTC, Andoran90 commented on Sources/ExchangeSdk/Public/Models/DTO/InfoDTO.swift
> +}
надо вынести в отдельный файл и переименовать:
`img` -> `image`
`imgColor` ->  `imageColor`

2022-10-31 06:30 UTC, Andoran90 commented on Sources/ExchangeSdk/Public/Models/DTO/LimitOrderDTO.swift
> +        case logID = "logId"
стоит убрать эти ключи, и переименовать в `logId`

2022-10-31 06:30 UTC, Andoran90 commented on Sources/ExchangeSdk/Public/Models/ParametersObject/LimitOrderParameters.swift
> +public enum Statuses: Int {
неудачное название. Лучше `ExchangeOrderStatus`
+ структуру файлов лучше поменять, сделать папку `LimitOrderParameters` и в нее сложить уже в разные файлы эти параметры

2022-10-31 06:30 UTC, Andoran90 commented on Sources/ExchangeSdk/Public/Models/ParametersObject/SwapParameters.swift
> +public struct QuoteParameters {
тот же коммент что и с `LimitOrderParameters`, надо разделить все на файлы и положить в папочку

2022-10-31 06:30 UTC, Andoran90 commented on Tests/ExchangeSdkTests/ExchangerTests.swift
> +            XCTAssert(true)
странные тесты получаются. что они тестируют?

на сколько я вижу в текущем варианте они тестируют работает ли сервак 1inch, но это не наша забота. Нам надо тестировать свой код, а не работу сервера.

2022-10-31 06:30 UTC, Andoran90 commented on Tests/ExchangeSdkTests/LimitTests.swift
> +            XCTAssert(true)
то же что и с предыдущими тестами. Можно, конечно, тестировать что возвращает сервер 1Inch, чтобы в какой-то момент мы могли отловить что на серваке у них что-то поменялось, но тесты с печатанием в консоль не имеют смысла. Надо либо проверять что конкретно в каждом объекте лежит и валидировать, что действительно полигоновский ответ пришел, либо убрать эти тесты вообще и тестировать свой код.
Я за второй вариант больше, т.к. первый, повторюсь, не наша забота. Мы первым вариантом может немного облегчить поиск проблемы, но для этого надо парсить все ответы и сверять информацию, а не просто печатать в консоль её

2022-10-31 06:30 UTC, Andoran90 commented on Sources/ExchangeSDK/ExchangeSdk.swift
> +}
бессмысленная структура. Надо либо через неё создавать `ExchangeService` и `LimitOrderService`, либо чтобы она была фасадом для всего фреймворка и при инициализации понимала с каким обменником мы работаем и в дебажном режиме или нет

2022-10-31 06:32 UTC, Andoran90 commented
А почему просто Package? Я думаю надо добавить нормально проект, таргеты. Так проще использовать. Наверняка мы потом добавим демо приложение. + мы можем узнать покрытие тестами, сейчас нет таргетов, у которых можно посмотреть покрытие тестами.

2022-10-31 14:10 UTC, gre4ixin commented on Sources/ExchangeSdk/API/ExchangeConstants.swift
> +struct ExchangeConstants {
у enum не получится сразу возвращать URL

2022-10-31 14:13 UTC, gre4ixin commented on Sources/ExchangeSdk/API/ExchangeTargets/SwapTarget.swift
> +    // find the best quote to exchange via 1inch router
✅

2022-10-31 14:13 UTC, gre4ixin commented on Sources/ExchangeSdk/API/ExchangeTargets/ApproveTarget.swift
> +enum InchApprove {
✅

2022-10-31 14:13 UTC, gre4ixin commented on Sources/ExchangeSdk/API/LimitTargets/LimitOrder.swift
> +//  LimitOrder.swift
✅

2022-10-31 14:18 UTC, gre4ixin commented on Sources/ExchangeSdk/Network/NetworkFacade.swift
> +class NetworkFacade {
✅

2022-10-31 16:09 UTC, gre4ixin commented
> А почему просто Package? Я думаю надо добавить нормально проект, таргеты. Так проще использовать. Наверняка мы потом добавим демо приложение. + мы можем узнать покрытие тестами, сейчас нет таргетов, у которых можно посмотреть покрытие тестами.
<img width="1197" alt="Снимок экрана 2022-10-31 в 19 08 17" src="https://user-images.githubusercontent.com/38533411/199055179-7e0ea942-24c0-45c8-8f16-4a88e5f04f92.png">

2022-10-31 16:26 UTC, gre4ixin commented on Sources/ExchangeSdk/Public/ExchangingFacade.swift
> +public class ExchangeFacade: ExchangingFacade {
✅

2022-10-31 16:37 UTC, gre4ixin commented on Sources/ExchangeSdk/Public/LimitOrderFacade.swift
> +public class LimitOrderService: LimitOrderFacade {
✅

2022-10-31 17:00 UTC, gre4ixin commented on Sources/ExchangeSdk/Public/Models/DTO/InfoDTO.swift
> +//  InfoDTO.swift
✅

2022-10-31 17:06 UTC, gre4ixin commented on Sources/ExchangeSdk/Public/Models/DTO/InfoDTO.swift
> +public struct InfoTokensDTO: Decodable {
✅

2022-10-31 17:09 UTC, gre4ixin commented on Sources/ExchangeSdk/Public/Models/DTO/InfoDTO.swift
> +}
✅

2022-10-31 17:10 UTC, gre4ixin commented on Sources/ExchangeSdk/Public/Models/ParametersObject/LimitOrderParameters.swift
> +public enum Statuses: Int {
✅

2022-10-31 17:12 UTC, gre4ixin commented on Sources/ExchangeSdk/Public/Models/DTO/LimitOrderDTO.swift
> +        case logID = "logId"
✅

2022-10-31 17:13 UTC, gre4ixin commented on Sources/ExchangeSDK/ExchangeSdk.swift
> +}
✅

2022-10-31 21:53 UTC, gre4ixin commented on Sources/ExchangeSdk/Network/NetworkFacade.swift
> +                        print("URL REQUEST -> \(response.request?.url?.absoluteString ?? "")")
лучше это в отдельной задаче сделать, иначе я закопаюсь

2022-10-31 22:02 UTC, gre4ixin commented on Sources/ExchangeSdk/API/ExchangeTargets/InfoTarget.swift
> +    case liquiditySources(blockchain: ExchangeBlockchain)
✅

2022-10-31 22:12 UTC, gre4ixin commented on Sources/ExchangeSdk/Network/NetworkFacade.swift
> +    func request<T: Decodable>(with target: BaseTarget, decodingObject: T.Type) async -> Result<T, ExchangeError> {
✅

2022-10-31 22:12 UTC, gre4ixin commented on Sources/ExchangeSdk/Public/Models/DTO/ApproveDTO.swift
> +}
убрал DTO, переименовал модели

2022-10-31 22:13 UTC, gre4ixin commented on Sources/ExchangeSdk/Public/Models/DTO/InfoDTO.swift
> +public struct TokenDTO: Decodable {
✅

2022-10-31 22:24 UTC, gre4ixin commented on README.md
> +```swift
✅

2022-11-01 06:08 UTC, Andoran90 requested changes

2022-11-01 06:08 UTC, Andoran90 commented on Sources/ExchangeSdk/Network/ExchangeNetworkService.swift
> +    }
думаю стоит переделать эту функцию и вызывать её для логирования парсинга
```suggestion
    private func logIfNeeded<T: Decodable>(data: Data, decodeTo: T.Type) {
        guard isDebug else { return }
        
        do {
            let decodeJSON = try JSONSerialization.jsonObject(with: data, options: .mutableContainers)
            let dataJSON = try JSONSerialization.data(withJSONObject: decodeJSON, options: .prettyPrinted)
            print(String(decoding: dataJSON, as: UTF8.self))
        } catch {
            print("Decoding response error -> \(error)")
        }
    }
```

2022-11-01 06:08 UTC, Andoran90 commented on Sources/ExchangeSdk/Network/ExchangeNetworkService.swift
> +    let debugMode: Bool
думаю тут лучше назвать: isDebug. Для булок лучше использовать is... Везде стоит изменить

2022-11-01 06:08 UTC, Andoran90 commented on Sources/ExchangeSdk/Network/ExchangeNetworkService.swift
> +                            continuation.resume(returning: .success(object))
и вот сюда можно добавить logIfNeeded для ответа

2022-11-01 06:08 UTC, Andoran90 commented on Sources/ExchangeSdk/Network/ExchangeNetworkService.swift
> +                            let errorObject = try self.jsonDecoder.decode(InchError.self, from: response.data)
а сюда logIfNeeded для попытки распарсить ошибку, чтобы и тот и другой вариант пошли в логи

2022-11-01 07:57 UTC, gre4ixin commented on Sources/ExchangeSdk/Public/Models/DTO/HealthCheckDTO.swift
> +    public let status: String
у них в этом запросе так себе описание, не понятно что может еще прийти кроме "ОК"

2022-11-01 08:38 UTC, gre4ixin commented on Sources/ExchangeSdk/Public/Models/DTO/ApproveDTO.swift
> +//  ApproveSpenderDTO.swift
✅

2022-11-01 08:39 UTC, gre4ixin commented on Sources/ExchangeSdk/Public/Models/DTO/HealthCheck.swift
> +    public let status: String
списка возможных нет, поэтому лучше оставить строкой, к сожалению

2022-11-01 08:39 UTC, gre4ixin commented on Sources/ExchangeSdk/Public/Models/DTO/SwapData.swift
> +public struct QuoteData: Decodable {
✅

2022-11-01 08:44 UTC, gre4ixin commented on Sources/ExchangeSdk/Network/ExchangeNetworkService.swift
> +    let debugMode: Bool
✅

2022-11-01 08:47 UTC, gre4ixin commented on Sources/ExchangeSdk/Network/ExchangeNetworkService.swift
> +                            continuation.resume(returning: .success(object))
✅

2022-11-01 08:49 UTC, gre4ixin commented on Sources/ExchangeSdk/Network/ExchangeNetworkService.swift
> +                            let errorObject = try self.jsonDecoder.decode(InchError.self, from: response.data)
✅

2022-11-01 08:51 UTC, gre4ixin commented on Tests/ExchangeSdkTests/LimitTests.swift
> +        let params = AllOrdersParameters.init(statuses: [.invalid, .temporaryInvalid])
✅

2022-11-01 09:27 UTC, gre4ixin commented on Sources/ExchangeSdk/Network/ExchangeNetworkService.swift
> +    }
✅

2022-11-01 11:22 UTC, gre4ixin commented on Sources/ExchangeSdk/Network/ExchangeNetworkService.swift
> +                    }
✅

2022-11-01 11:23 UTC, Andoran90 approved these changes

2022-11-01 11:25 UTC, merged